sudo: required

services: 
    - docker

before_install:
    - docker pull socalucr/gpgpu-sim

language: cpp


script: docker run -v ${TRAVIS_BUILD_DIR}:/root/src/ socalucr/gpgpu-sim /bin/bash -c "cd gpgpu-sim_distribution/; source setup_environment; make; cd /root/src/; make; ./sgemm-tiled; "

